### ISSUE TITLE
Missing variable replacements in css files

### ISSUE THREAD

**Issue by cgmartin** [topcoat/topcoat#334]
Encountered style issues with some components using the `topcoat-mobile-dark.css` file as-is. It looked like missing variable replacements might be the cause. 

Example:

``` css
.topcoat-overlay {
  /* ... */
  padding: var-overlay-padding;
  background-color: var-bg-color;
  /* ... */
}
```

Found 11 instances of "var-" in https://github.com/topcoat/topcoat/blob/3aaa7b732688b77722f3ff4b83758158ad559140/css/topcoat-mobile-dark.css
