### ISSUE TITLE
Create search input base component

### ISSUE THREAD

**Issue by kristoferjoseph** [topcoat/topcoat#365]
We need to create a specific search input base component in order to add the specific reset of removing the clear button so the component looks consistent across platforms.

``` css
input[type="search"]::-webkit-search-cancel-button {
    -webkit-appearance: none;
}
```
