### ISSUE TITLE
Default header height on mobile too tall

### ISSUE THREAD

**Issue by gregsramblings** [topcoat/topcoat#424]
Current header height is 4rem, which is too tall for mobile, especially on an iPhone 4 (3.5" screen) with the keyboard raised.

Most apps are more in the 3rem range.  I suggest we change the following:

``` css
.topcoat-navigation-bar__item {
    height: 3rem;
    line-height: 3rem;
}

.topcoat-navigation-bar {
    height: 3rem;
}
```

Thanks!

Greg
